services:
  backend:
    container_name: todo-app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - "8080:3000"
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16-alpine3.20
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.9
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgresql_data:
  pgadmin_data:
